"use client";

import { AlertCircle, CheckCircle2, Download, FileSpreadsheet, LoaderCircle, Upload, X } from "lucide-react";
import { ChangeEvent, useRef, useState } from "react";

type ImportedUser = { displayName: string; email: string; role: "admin" | "teacher" | "student"; className: string };
type Cell = string | number | boolean | Date | null | undefined;

function text(value: Cell) { return value instanceof Date ? value.toISOString() : value == null ? "" : String(value).trim(); }
function csvRows(source: string) { const rows: string[][] = []; let row: string[] = [], value = "", quoted = false; for (let i = 0; i < source.length; i += 1) { const char = source[i], next = source[i + 1]; if (char === '"') { if (quoted && next === '"') { value += '"'; i += 1; } else quoted = !quoted; } else if (char === "," && !quoted) { row.push(value); value = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && next === "\n") i += 1; row.push(value); rows.push(row); row = []; value = ""; } else value += char; } if (value || row.length) { row.push(value); rows.push(row); } return rows; }

function parse(rows: Cell[][]) {
  const filtered = rows.filter((row) => row.some((cell) => text(cell)));
  const headers = (filtered[0] || []).map((cell) => text(cell).toLowerCase().replace(/[_-]+/g, " "));
  const column = (...names: string[]) => headers.findIndex((header) => names.includes(header));
  const indexes = { name: column("full name", "name", "display name"), email: column("email", "email address"), role: column("role", "account role"), className: column("class", "class name") };
  const errors: string[] = [], users: ImportedUser[] = [];
  if (indexes.name < 0 || indexes.email < 0 || indexes.role < 0) return { users, errors: ["Required columns: Full Name, Email and Role."], rows: 0 };
  filtered.slice(1, 251).forEach((row, index) => { const displayName = text(row[indexes.name]), email = text(row[indexes.email]).toLowerCase(), role = text(row[indexes.role]).toLowerCase(), className = indexes.className >= 0 ? text(row[indexes.className]) : ""; const issues = []; if (!displayName) issues.push("name missing"); if (!/^\S+@\S+\.\S+$/.test(email)) issues.push("invalid email"); if (!["admin", "teacher", "student"].includes(role)) issues.push("role must be admin, teacher or student"); if (role === "student" && !className) issues.push("student class missing"); if (issues.length) errors.push(`Row ${index + 2}: ${issues.join("; ")}.`); else users.push({ displayName, email, role: role as ImportedUser["role"], className }); });
  return { users, errors, rows: Math.max(0, filtered.length - 1) };
}

export function BulkAccountImporter({ onComplete }: { onComplete: (message: string, error?: boolean) => void }) {
  const [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [fileName, setFileName] = useState(""), [parsed, setParsed] = useState<ReturnType<typeof parse> | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const close = () => { setOpen(false); setBusy(false); setFileName(""); setParsed(null); if (inputRef.current) inputRef.current.value = ""; };
  const handle = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setBusy(true); setFileName(file.name); try { let rows: Cell[][]; if (file.name.toLowerCase().endsWith(".csv")) rows = csvRows(await file.text()); else if (file.name.toLowerCase().endsWith(".xlsx")) { const { default: readXlsxFile } = await import("read-excel-file/browser"); rows = await readXlsxFile(file); } else throw new Error("Choose a CSV or Excel (.xlsx) file."); setParsed(parse(rows)); } catch (error) { setParsed({ users: [], errors: [error instanceof Error ? error.message : "File could not be read."], rows: 0 }); } finally { setBusy(false); } };
  const upload = async () => { if (!parsed?.users.length || parsed.errors.length) return; setBusy(true); try { const response = await fetch("/api/admin/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ users: parsed.users }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Import failed."); onComplete(`${payload.imported} school accounts imported.`); close(); } catch (error) { onComplete(error instanceof Error ? error.message : "Import failed.", true); setBusy(false); } };
  return <><button className="admin-secondary-button" type="button" onClick={() => setOpen(true)}><Upload size={15} />Bulk import</button>{open && <div className="dialog-backdrop admin-dialog-backdrop"><section className="studio-dialog import-dialog"><button className="dialog-close" onClick={close}><X size={18} /></button><span className="dialog-icon amber"><FileSpreadsheet size={23} /></span><p className="eyebrow">Account import</p><h2>Import students and staff</h2><p className="dialog-description">Upload up to 250 approved accounts from CSV or Excel. Students must include a class.</p><a className="account-template-link" href="/school-accounts-template.csv" download><Download size={14} />Download account template</a><label className={`question-file-drop${fileName ? " has-file" : ""}`}>{busy ? <LoaderCircle className="spin" size={23} /> : <Upload size={23} />}<span><strong>{fileName || "Choose account file"}</strong><small>CSV or Excel (.xlsx)</small></span><input ref={inputRef} type="file" accept=".csv,.xlsx" onChange={(event) => void handle(event)} /></label>{parsed && <div className={`import-result${parsed.errors.length ? " has-errors" : " valid"}`}><div className="import-result-summary">{parsed.errors.length ? <AlertCircle size={18} /> : <CheckCircle2 size={18} />}<span><strong>{parsed.errors.length ? "Please fix the account file" : `${parsed.users.length} accounts ready`}</strong><small>{parsed.errors.length ? `${parsed.errors.length} issues in ${parsed.rows} rows.` : "Names, emails, roles and student classes passed validation."}</small></span></div>{parsed.errors.length > 0 && <ul className="import-errors">{parsed.errors.slice(0, 8).map((item) => <li key={item}>{item}</li>)}</ul>}</div>}<div className="dialog-actions import-actions"><button onClick={close}>Cancel</button><button className="solid-action" disabled={busy || !parsed?.users.length || Boolean(parsed.errors.length)} onClick={() => void upload()}><Upload size={14} />Import accounts</button></div></section></div>}</>;
}
